---
- name: Install samba
  apt: name={{ packages }} state=latest
  notify:
    - Install {{ packages }}
- name: Copy config files
  copy: src=smb.conf dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - Copy config files
- name: Create share dirs
  file:
    path: /home/forms
    state: directory
  notify:
    - Create share dirs