---
- include: fix.yml
- include: docker.yml
  when: "'service' in group_names"
- name: Install APT packages
  apt: name={{ apt_packages }} state=latest
  when: ansible_os_family == "Debian"
- name: Install YUM packages
  yum: name={{ yum_packages }} state=latest
  when: ansible_os_family == "RedHat"
- name: Disable SELinux
  selinux: state=disabled
  when: ansible_os_family == "RedHat"
- name: Set timezone to Europe/Kiev
  timezone:
    name: Europe/Kiev